# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170908_1414'),
    ]

    operations = [
    ]
